version: '3.1'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: